### ISSUE TITLE
" test_kwave_helmholtz_fd.py "

### ISSUE THREAD

**Issue by gangwonee** [ucl-bug/jwave#127]
Hi, Can I ask about some bugs here?
When executing this script, it returns
"plum.function.NotFoundLookupError: For function "gradient", signature Signature(jaxdf.discretization.FiniteDifferences, builtins.list) could not be resolved."
It seems only "FourierSeries" is used for solving helmholtz for now.

**Comment by astanziola** [comment]
I think this is due to the recent update of jaxdf. I'll fix this after Christmas :) Thanks for pointing it out!

**Comment by gangwonee** [comment]
Thank you! And I tried to compare solution of Helmholtz equation on homogeneous media via running  with the analytic solution.
The baseline code was "https://github.com/ucl-bug/jwave/blob/main/tests/test_helmholtz.py". I also found that the GMRES solution converged well, but when I applied IFFT to the trace and compare it with analytic solution, it seemed like traveltime was wrong. Phase may not be correctly resolved..? I assume that the code were verified by comparison with kWave solution in the frequency domain, not transformed in the time domain, am I right? Thank you

**Comment by astanziola** [comment]
Hopefully this is fixed by #123 , which is not upstreamed to the main branch. Feel free to reopen this issue if the problem persists!

**Comment by gangwonee** [comment]
Thank you! Still there is an issue with 'gradient' to the FD field like,
`NotFoundLookupError: For function "gradient", signature Signature(jaxdf.discretization.FiniteDifferences, builtins.list) could not be resolved.`
but I will look at it. Thanks

**Comment by astanziola** [comment]
That is odd since all tests seem to pass here on GitHub. Did you reinstall from scratch? Note that some requirements have been updated too.
