### ISSUE TITLE
NaNs when batching simulations in tutorial example.

### ISSUE THREAD

**Issue by talfanoutlook** [ucl-bug/jwave#168]
**Describe the bug**
Hi guys, I am trying to reproduce the Full Wave Inversion tutorial example. When batching the single simulation across sensor indices with `jax.vmap`, I am getting NaNs, even though running those sensor simulations individually runs stably.

I'm running on a Colab with GPU.

**To Reproduce**
Colab to reproduce:

https://colab.research.google.com/drive/1U3ttIMkn4lZnlu4SMNf4Y0IcuB7Sv9MH?usp=sharing

**Expected behavior**
Batching vs. looping over single sensor simulations should produce the same result.

**Desktop (please complete the following information):**
 - Running on Google Colab with GPU.

**Comment by talfanoutlook** [comment]
Great let me know - I'll try to take a look myself also.

**Comment by astanziola** [comment]
I have a feeling that the library behind jwave (jaxdf) needs to be upgraded to the most recent jax versions, so maybe give me a bit to check that out before getting lost in the code :)

**Comment by talfanoutlook** [comment]
Hey Antonio, any suggestions on where to get started? Happy to dig in you you don’t have the time rn.

Talfan

Sent from my iPhone

On 3 May 2023, at 16:50, Antonio Stanziola ***@***.***> wrote:

﻿

I have a feeling that the library behind jwave (jaxdf) needs to be upgraded to the most recent jax versions, so maybe give me a bit to check that out before getting lost in the code :)

**Comment by astanziola** [comment]
Hi @talfanoutlook , I might need another couple of days on this sorry.
I'm fixing a few issues with `jaxdf` first that arised with the new jax version, and then will jump on it.
If you find anything meanwhile feel very free to update here or PR!

**Comment by astanziola** [comment]
@talfanoutlook Just to let you know that I haven't forgot about this, but the problem is weirder than I expected.

What is happening is that if I run twice the same exact (jitted!) function, in this case `single_source_simulation`, with the same arguments, sometimes I get two different results. It seems that there's something stored in memory that is affecting the results, which is definetely something unexpected from a funcional programmin language like `jax`, so it's not immediately obvious to me what the issue is.

**Comment by talfanoutlook** [comment]
That’s great Antonio, thanks for looking into this.

Excited to start using jwave :)

Sent from my iPhone

On 23 May 2023, at 15:27, Antonio Stanziola ***@***.***> wrote:

﻿

Interestingly enough, if one disables GPUs and runs the code on CPU, the issue does not appear.
That explains why the tests tha run against k-Wave do not fail.

I'll try to setup an MRE and raise it to the jax team.

**Comment by astanziola** [comment]
Made a MRE and raised to the `jax` team: https://github.com/google/jax/issues/16129

**Comment by talfanoutlook** [comment]
That's awesome Antonio - I'll follow the the link!
________________________________

**Comment by talfanoutlook** [comment]
Very weird bug indeed. Is it specifically in the sinc function as far as you can tell?
________________________________

**Comment by astanziola** [comment]
Something related to it, but quite weird to just have to do with the sinc.

A quick way to avoid this problem for now is to get rid of the k-space
correction (by overloading the `params` of `simulate_wave_propagation`, and
setting the k-space operator to all ones manually). It should not matter
too much for simulations of the order of tens of wavelengths (see the
paragraphs around eq. (2.15) and (2.16) of the k-wave manual
www.k-wave.org/manual/k-wave_user_manual_1.1.pdf ).

I will add an example about how to disable it in the next release.

Il giorno ven 26 mag 2023 alle ore 11:37 talfanoutlook <
***@***.***> ha scritto:
